# Usamos una imagen base de Python
FROM python:3.9-slim

# Establecemos el directorio de trabajo
WORKDIR /app

# Copiamos el archivo de script a la imagen
COPY hello.py .

# Comando para ejecutar el script de Python
CMD ["python", "hello.py"]
